language: scala
scala:
   - 2.12.1

script: "sbt ++$TRAVIS_SCALA_VERSION coverage test"
after_success:
   - "bash <(curl -s https://codecov.io/bash)"
   - "sbt coverageReport codacyCoverage"
   - "sbt ++$TRAVIS_SCALA_VERSION versioneye:updateProject"

jdk:
  - oraclejdk8

# Use container-based infrastructure
sudo: false

env:
  global:
    #VERSIONEYE_API_KEY=xxx CODACY_PROJECT_TOKEN=xxx
    secure: "jUsWTvzIysLe2K5+6una3nngMjb6TiebiuyzQzMYE9ZrYY6MfxPSvDlQ6Y/BmpdZIaOoJSVZsi1eSTqQejlWhZISaZ4U38of6/QtAmwCmroYogs7X7ctvKkppWEWM/BMZXm6Iu/+BFOCvdu+1Vu4yG0L0GQi58Qf+IuhUKrnBQZi5MmXZYdvLQML5b5It49oSj4aBh3PXjv6r1+dSfmJXAJi+aehMPOnEVwqiPPUlcAq2xwLdPzC5tH2OafEz2kTk9MGHxsLgsp74cIh36fA9sS+Oet5WamD5Y+ax9UcR/hWxLVSAixE7F457UlfaeKkjnLhKWs/vVnRaDlJHFSkLNWnfykuvmNR/zN8qheWOOz8KK4VW3Jpo1MAZa9cPkYohzTr/JjDsvBcgs8uNj/rxTRKVwEDuQa+/pN2oyd+8lWvXhplG1WFSREh3aTWC/WJX7ZicjgNpoz5fLqN5P1ESqig3qTUy8vl44nIgcFRBDQqfHlNEWn/f+c5X23xDQskX/mBXq/H1/AqWlBaGa/DsPLp/m/Jap+Sb7W0vQ4C7+heBsemhZyjglEeLydJkAywC/pDokStVRnER77mvddCW0HjrLfa10jYZtyoM+vR1vsKzM3tC//H9cMW3bmQxLRRE/xts7V0+ItCevBJI4ZyPlZMDCQLKeZePu/GotfO6Vo="


cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

notifications:
  slack:
    rooms: dingsteam:RAMFhHHEJFRie1VmpxfhKnix
    on_success: always
    on_failure: always
    on_start: never
    on_pull_requests: false